cleanup

diff --git a/check_ipvsadm b/check_ipvsadm
--- a/check_ipvsadm
+++ b/check_ipvsadm
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -euo pipefail
 
 #################### INPUT AND ERROR HANDLING ########################
 
@@ -7,7 +8,6 @@ CRIT=0
 PROTO='-t'
 PROTO_HUMAN=tcp
 ME="$(basename $0)"
-IPV4_AND_PORT='([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]+'
 
 error() {
     printf "${@}\n\n" >&2
@@ -29,6 +29,13 @@ Usage example: $ME -v 192.168.0.1:80 -t -w1 -c0\n\n" >&2
     exit 3
 }
 
+scrape_ipv4_and_port() {
+  [[ -z $1 ]] && error "function ${FUNCNAME[0]} requires a parameter."
+  echo $@ | grep -swoE "([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]+"
+  return $?
+
+}
+
 [[ ! -x $(which ipvsadm) ]] && error "ipvsadm not found in PATH. Install ipvsadm and run as root."
 
 while getopts ":htuv:w:c:" opt; do
@@ -46,15 +53,14 @@ while getopts ":htuv:w:c:" opt; do
 done
 
 [[ -z $PATTERN ]] && usage
-echo "$PATTERN" | grep -sqwE "$IPV4_AND_PORT" || error "Bad IPv4 address or port: $PATTERN" 
-
+scrape_ipv4_and_port $PATTERN > /dev/null || error "Bad IPv4 address or port: $PATTERN" 
 
 ################## MAIN ###########################
 
-OUTPUT=$(ipvsadm -L -n $PROTO $PATTERN 2> /dev/null)  || error "Virtual server $PATTERN/$PROTO_HUMAN not found."
-UP+=( $(echo "$OUTPUT" | tail -n +4 | grep -woE "$IPV4_AND_PORT") ) 
+OUTPUT=$(ipvsadm -L -n $PROTO $PATTERN 2> /dev/null | tail -n +4) || error "Virtual server $PATTERN/$PROTO_HUMAN not found."
+UP=( $(scrape_ipv4_and_port $OUTPUT) ) 
 
-if [[ -z ${UP} ]]; then
+if [[ ! -v UP ]]; then
     echo "CRITICAL: 0 up."
     exit 2
 
